### ISSUE TITLE
the mongo-oplog-backup no install

### ISSUE THREAD

**Issue by samerkalil** [journeyapps/mongo-oplog-backup#12]
~~~
LoadError: cannot load such file -- bundler/gem_tasks
/home/mongo-oplog-backup-master/Rakefile:1:in `<top (required)>'
(See full trace by running task with --trace)
~~~

**Comment by rkistner** [comment]
@samerkalil Which version of bundler and ruby are you using?

**Comment by amardeokar23** [comment]
Step to install on Ubuntu.
sudo apt-get install ruby-dev
sudo gem install bundler
git clone https://github.com/journeyapps/mongo-oplog-backup.git
cd mongo-oplog-backup
sudo bundle install
sudo rake install

**Comment by rkistner** [comment]
This project is not being maintained anymore - closing all issues.
