### ISSUE TITLE
--file option doesnt not have any effect

### ISSUE THREAD

**Issue by amardeokar23** [journeyapps/mongo-oplog-backup#16]
As stated command line option will take precedence over values passed through config file. 
But if we dont pass command line option like host/post even in that case values/options passed through config file are not considered, due to default value/nil value got set before reading options from config file.

Below are the default values which are set before reading options from file.
> {:dir=>"backup", :gzip=>true, :ssl=>false, :sslAllowInvalidCertificates=>false, :host=>"localhost", :port=>"27017", :username=>nil, :password=>nil, :sslCAFile=>nil}

Code which overrides file options from lib/mongo_oplog_backup/config.rb 
`@options = from_file(config_file).merge(options)`

**Comment by rkistner** [comment]
This project is not being maintained anymore - closing all issues.
