### ISSUE TITLE
Incremental backup fails with JSON error

### ISSUE THREAD

**Issue by amanpal2412** [journeyapps/mongo-oplog-backup#18]
The initial full backup works fine, but when running the incremental backup it gives invalid JSON error

`I, [2020-01-27T14:01:08.176509 #5679]  INFO -- : Performing incremental oplog backup
D, [2020-01-27T14:01:08.202245 #5679] DEBUG -- : >>> mongodump --host prod-mongo-shard-2-a.mlprivate.net --port 27018 --out /mnt/efs/25-01-20/tmp-dump --db local --collection oplog.rs --query \{ts\ :\ \{\ \$gte\ :\ \{\ \$timestamp\ :\ \{\ t\ :\ 1579891808,\ i\ :\ 1\ \}\ \}\ \}\}
E, [2020-01-27T14:01:08.260854 #5679] ERROR -- : 2020-01-27T14:01:08.260+0000   Failed: error parsing query as Extended JSON: invalid JSON input
`

Not sure what the issue is here.

**Comment by rkistner** [comment]
What version of mongodb and mongodump are you using? It's likely that it's a compatibility issue with newer versions.

**Comment by rkistner** [comment]
This project is not being maintained anymore - closing all issues.
