### ISSUE TITLE
merging oplogs with until to specific date options

### ISSUE THREAD

**Issue by hbakhtiyor** [journeyapps/mongo-oplog-backup#7]
would be nice to add date filter for merging oplogs,

something like this
e.g. `mongo-oplog-backup merge --until string`
the options can accept an rfc 3339 date, a unix timestamp, or a duration string (e.g. 5h ago).

**Comment by rkistner** [comment]
Yes, that would be useful. Pull requests are welcome.

**Comment by rkistner** [comment]
This project is not being maintained anymore - closing all issues.
